name: Deploy to Production

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_REGION: ${{ vars.GCP_REGION }}
  GAR_REPOSITORY: "pairreader"
  GAR_BASE_IMAGE_NAME: "pairreader"
  CLOUDRUN_BASE_SERVICE_NAME: "pairreader-service"

on:
  workflow_dispatch:
    inputs:
      confirm_production:
        description: 'Type "production" to confirm deployment'
        required: true
        type: string

# Prevent concurrent deployments to production
concurrency:
  group: production-deployment
  cancel-in-progress: false

jobs:
  validate-input:
    name: Validate production confirmation
    runs-on: ubuntu-latest
    steps:
      - name: Check confirmation
        run: |
          if [ "${{ github.event.inputs.confirm_production }}" != "production" ]; then
            echo "Error: You must type 'production' to confirm deployment"
            exit 1
          fi
          echo "Production deployment confirmed"

  extract-version:
    name: Extract versions
    runs-on: ubuntu-latest
    needs: validate-input
    outputs:
      PAIRREADER_VERSION: ${{ steps.extract-versions.outputs.PAIRREADER_VERSION }}
      TF_VERSION: ${{ steps.extract-versions.outputs.TF_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Extract versions
        id: extract-versions
        run: |
          PAIRREADER_VERSION=$(grep -m 1 '^version = ' pyproject.toml | sed 's/version = "\(.*\)"/\1/')
          TF_VERSION=$(cat infra/.terraform-version)
          echo "PAIRREADER_VERSION = $PAIRREADER_VERSION"
          echo "TF_VERSION = $TF_VERSION"
          echo "PAIRREADER_VERSION=$PAIRREADER_VERSION" >> $GITHUB_OUTPUT
          echo "TF_VERSION=$TF_VERSION" >> $GITHUB_OUTPUT

  terraform-plan-prod:
    name: Terraform plan (prod)
    runs-on: ubuntu-latest
    needs: extract-version
    environment: gcp
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ needs.extract-version.outputs.TF_VERSION }}

      - name: Authenticate to Google Cloud
        run: |
          echo '${{ secrets.SA }}' > ${HOME}/gcp-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
          gcloud config set project ${{ env.GCP_PROJECT_ID }}
          rm ${HOME}/gcp-key.json

      - name: Terraform Init
        run: terraform init
        working-directory: infra/envs/prod

      - name: Terraform Plan
        run: terraform plan -var-file=../../terraform.tfvars
        working-directory: infra/envs/prod

  terraform-apply-prod:
    name: Terraform apply (prod)
    runs-on: ubuntu-latest
    needs:
      - extract-version
      - terraform-plan-prod
    environment: gcp
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ needs.extract-version.outputs.TF_VERSION }}

      - name: Authenticate to Google Cloud
        run: |
          echo '${{ secrets.SA }}' > ${HOME}/gcp-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
          gcloud config set project ${{ env.GCP_PROJECT_ID }}
          rm ${HOME}/gcp-key.json

      - name: Terraform Init
        run: terraform init
        working-directory: infra/envs/prod

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=../../terraform.tfvars
        working-directory: infra/envs/prod

  docker-build-prod:
    name: Build and push Docker (prod)
    runs-on: ubuntu-latest
    needs:
      - extract-version
      - terraform-apply-prod
    environment: gcp
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Authenticate to Google Cloud
        run: |
          echo '${{ secrets.SA }}' > ${HOME}/gcp-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
          gcloud config set project ${{ env.GCP_PROJECT_ID }}
          rm ${HOME}/gcp-key.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG="${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}-prod/${{ env.GAR_BASE_IMAGE_NAME }}-prod:v${{ needs.extract-version.outputs.PAIRREADER_VERSION }}"
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

  deploy-prod:
    name: Deploy to Cloud Run (prod)
    runs-on: ubuntu-latest
    needs:
      - extract-version
      - docker-build-prod
    environment: gcp
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Authenticate to Google Cloud
        run: |
          echo '${{ secrets.SA }}' > ${HOME}/gcp-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
          gcloud config set project ${{ env.GCP_PROJECT_ID }}
          rm ${HOME}/gcp-key.json

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.CLOUDRUN_BASE_SERVICE_NAME }}-prod \
            --image=${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GAR_REPOSITORY }}-prod/${{ env.GAR_BASE_IMAGE_NAME }}-prod:v${{ needs.extract-version.outputs.PAIRREADER_VERSION }} \
            --region=${{ env.GCP_REGION }} \
            --service-account=pairreader-runtime-prod@${{ env.GCP_PROJECT_ID }}.iam.gserviceaccount.com \
            --no-allow-unauthenticated \
            --memory=4Gi \
            --port=8000 \
            --set-secrets=ANTHROPIC_API_KEY=ANTHROPIC_API_KEY:latest,CHAINLIT_AUTH_SECRET=CHAINLIT_AUTH_SECRET:latest,LANGSMITH_API_KEY=LANGSMITH_API_KEY:latest \
            --quiet

      - name: Get Service URL
        run: |
          SERVICE_URL=$(gcloud run services describe ${{ env.CLOUDRUN_BASE_SERVICE_NAME }}-prod \
            --region=${{ env.GAR_LOCATION }} \
            --format='value(status.url)')
          echo "Production service deployed at: $SERVICE_URL"
