name: Deploy to Staging

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_REGION: ${{ vars.GCP_REGION }}
  GAR_REPOSITORY: "pairreader"
  GAR_BASE_IMAGE_NAME: "pairreader"
  CLOUDRUN_BASE_SERVICE_NAME: "pairreader-service"

on:
  workflow_dispatch:

# Prevent concurrent deployments to staging
concurrency:
  group: staging-deployment
  cancel-in-progress: false

jobs:
  extract-version:
    name: Extract versions
    runs-on: ubuntu-latest
    outputs:
      PAIRREADER_VERSION: ${{ steps.extract-versions.outputs.PAIRREADER_VERSION }}
      TF_VERSION: ${{ steps.extract-versions.outputs.TF_VERSION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Extract versions
        id: extract-versions
        run: |
          PAIRREADER_VERSION=$(grep -m 1 '^version = ' pyproject.toml | sed 's/version = "\(.*\)"/\1/')
          TF_VERSION=$(cat infra/.terraform-version)
          echo "PAIRREADER_VERSION = $PAIRREADER_VERSION"
          echo "TF_VERSION = $TF_VERSION"
          echo "PAIRREADER_VERSION=$PAIRREADER_VERSION" >> $GITHUB_OUTPUT
          echo "TF_VERSION=$TF_VERSION" >> $GITHUB_OUTPUT

  terraform-staging:
    name: Terraform (staging)
    needs: extract-version
    uses: ./.github/workflows/terraform-workflow.yml
    with:
      environment: staging
      terraform_version: ${{ needs.extract-version.outputs.TF_VERSION }}
      project_id: ${{ vars.GCP_PROJECT_ID }}
      region: ${{ vars.GCP_REGION }}
    secrets:
      SA: ${{ secrets.SA }}

  docker-build-staging:
    name: Build and push Docker (staging)
    needs:
      - extract-version
      - terraform-staging
    uses: ./.github/workflows/docker-build.yml
    with:
      environment: staging
      image_tag: ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/pairreader-staging/pairreader-staging:v${{ needs.extract-version.outputs.PAIRREADER_VERSION }}
      project_id: ${{ vars.GCP_PROJECT_ID }}
      region: ${{ vars.GCP_REGION }}
    secrets:
      SA: ${{ secrets.SA }}

  deploy-staging:
    name: Deploy to Cloud Run (staging)
    needs:
      - extract-version
      - docker-build-staging
    uses: ./.github/workflows/deploy-cloudrun.yml
    with:
      environment: staging
      image_tag: ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/pairreader-staging/pairreader-staging:v${{ needs.extract-version.outputs.PAIRREADER_VERSION }}
      project_id: ${{ vars.GCP_PROJECT_ID }}
      region: ${{ vars.GCP_REGION }}
      service_name: pairreader-service-staging
      allow_unauthenticated: true
    secrets:
      SA: ${{ secrets.SA }}
